### ISSUE TITLE
Lineup generator still not working

### ISSUE THREAD

**Issue by RDx55** [mkayen/DailyFBB-Engine#4]
I tested the latest branch and still no luck.

I  get the following when I run it.

It's still not working for me.

I am now getting this error

Promise {
_bitField: 0,
_fulfillmentHandler0: undefined,
_rejectionHandler0: undefined,
_promise0: undefined,
_receiver0: undefined,
_cancellationParent:
Promise {
_bitField: 1,
_fulfillmentHandler0: [Function],
_rejectionHandler0: undefined,
_promise0: [Circular],
_receiver0: undefined,
_cancellationParent:
Promise {
_bitField: 1,
_fulfillmentHandler0: undefined,
_rejectionHandler0: undefined,
_promise0: [Circular],
_receiver0: undefined,
_onCancelField: [Function],
_branchesRemainingToCancel: 1 },
_branchesRemainingToCancel: 1 } }
Player Data:
[]
Script has started to run. Please wait a few minutes for lineup to generate.
17 | 13 | 10 | 9 | 9
10 | 10 | 10 | 10 | 9
90000
100
0
undefined

**Comment by mkayen** [comment]
I'm going to document this better in my next code push, but if you go to
line 176 in crawler/nf.js, you'll see:

if(pos.pairs.length < 10){

Change 10 to a higher number (I chose 17)

In short, that 10 is saying that the script is trying to build a lineup
with the the top 10 pairs of positions (since you start two point guards)
and top 10 centers, as per numberfire's projections. Today, using only the
top 10 pairs of positions won't generate an eligible line-up (That is,
there is no way to build a lineup under cap using only the top 10 outputs
for each pair and center.

Increasing the number will have the script evaluate the top 17 eligible
lineups. In general, you'll get the best result possible the higher that
number is. However, when there are more games in a day, there's
significantly more potential lineups to process, so you'll want to keep the
number less so the script doesn't crash.

Max

**Comment by RDx55** [comment]
Perfect!! It works now. Thanks.

**Comment by mkayen** [comment]
No problem! Let me know how it goes!

**Comment by RDx55** [comment]
Another questions, the output before the list actually gets generated what does it represent. 

"
17 | 13 | 10 | 9 | 9
10 | 10 | 10 | 10 | 9
90000
100
0
"

**Comment by mkayen** [comment]
Mostly for my troubleshooting. Appreciate your feedback - I can clean this
up too. But here's the idea.:

Line 1 = The number of eligible players per positions ( PG | SG | SF | PF |
C ). Players who are more expensive and projected to put up less points
than less expensive players mathematically cannot be selected. So throwing
those players away (and ones projected to put up 0), we are left with the
number of players that could be selected per position.

Line 2 = The number of pairs to be evaluated. Position pairs (2 point
guards, for instance) are generated... given the restriction stated in line
176, it will take the top '10' pairs as per projected output. If you change
the number to 15, this will become 15. On this day, there are only 9
eligible centers.

Line 3 = Total lineups needed to be sorted through. Basically all the
numbers in line 2 multiplied against each other. I've found anything over
1M tends to crash, so I adjust line 176 to accommodate. I'm going to
automate this at some point...

Line 4 = Total number of point guard and shooting guard combinations after
sorting (10 * 10). Again, really for troubleshooting.

Line 5 = Total number of lineups that can be used as per pricing
restriction ($60k). In this case, there are 0 lineups eligible. This is an
indicator to increase the number used in line 176.

Also - If you are curious to see all of the eligible lineups (as per line
3), remove the [0] from allLineups in line 330. If you run 'node
crawler/nf.js > log.txt' in your terminal, you can save all these lineups
in a text file for you to go back to.

Hope this helps!

**Comment by RDx55** [comment]
That helps out a lot. Thanks.

**Comment by RDx55** [comment]
Can I make any changes to the code to exclude a certain player from the calculations?

**Comment by mkayen** [comment]
The way the code stands, there isn't. No input is really provided by the
user to the script today, you just run the script and out pops the lineups.

If you'd like to build it, please do!

On Thu, Jan 5, 2017, 5:37 PM RDx55 <notifications@github.com> wrote:

Can I make any changes to the code to exclude a certain player from the
calculations?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/mkayen/DailyFBB-Engine/issues/4#issuecomment-270778415>,
or mute the thread

**Comment by RDx55** [comment]
To speedup the process, what part of the code goes through the players? Line 77 to 105?

**Comment by mkayen** [comment]
77 -> 105 is the screen scrape of numberfire. It grabs the data the script
needs and dumps it into an array.

If you're trying to figure out how to remove a player, I'd suggest starting
with the check() function located on line 130. Line 133 basically takes the
sorted position array (ex. array with all point guards) by projected points
and checks that the salary is less than the next one. If it is, then remove
the next item...

You might be able to add something like ... & pos.arr[i][0]!='Player Name'
to the if statement on 133. you'd have to edit this prior to running the
script the way that it's written today though.
